apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: mungegithub
    track: alpha
    version: "2015-10-26-2a7f8fd"
  name: mungegithub-2015-10-26-2a7f8fd
  namespace: default
spec:
  replicas: 1
  selector:
    app: mungegithub
    track: alpha
    version: "2015-10-26-2a7f8fd"
  template:
    metadata:
      name: mungegithub
      namespace: default
      labels:
        app: mungegithub
        track: alpha
        version: "2015-10-26-2a7f8fd"
    spec:
      containers:
      - command:
        - /mungegithub
        - --token-file=/etc/secret-volume/token
        - --pr-mungers=blunderbuss,lgtm-after-commit,needs-rebase,ok-to-test,rebuild-request,path-label,size,stale-pending-ci,stale-green-ci,block-path,submit-queue
        - --dry-run=true
        image: gcr.io/google_containers/mungegithub:2015-10-26-2a7f8fd
        imagePullPolicy: IfNotPresent
        name: mungegithub
        ports:
        - name: status
          containerPort: 8080
        resources:
          limits:
            cpu: 100m
        volumeMounts:
        - mountPath: /etc/secret-volume
          name: secret-volume
        - mountPath: /gitrepos
          name: kubernetes-repo
      dnsPolicy: ClusterFirst
      volumes:
      - name: secret-volume
        secret:
          secretName: github-token
      - name: kubernetes-repo
        gitRepo:
          repository: "https://github.com/kubernetes/kubernetes.git"
          revision: "master"
