- name: Contiv | Wait for netmaster
  action: shell netctl tenant ls
  register: tenant_result
  until: tenant_result.stdout.find("default") != -1
  retries: 12
  delay: 10

- name: Contiv | Check if default-net exists
  action: shell netctl net ls
  register: net_result

- name: Contiv | Create default-net
  shell: netctl net create --subnet={{contiv_default_subnet}} default-net
  when: net_result.stdout.find("default-net") == -1

- name: Contiv | Create poc-net
  shell: netctl net create --subnet={{contiv_poc_subnet}} poc-net
  when: net_result.stdout.find("poc-net") == -1 and contiv_demo
