
- name: copy netmaster exec file
  copy: src={{ contiv_bin_path }}/netmaster dest=/usr/bin/netmaster mode=0755

- name: copy netctl exec file
  copy: src={{ contiv_bin_path }}/netctl dest=/usr/bin/netctl mode=0755

- name: copy contivctl exec file
  copy: src={{ contiv_bin_path }}/contivctl dest=/usr/bin/contivctl mode=0755

- name: copy netmaster setup script
  copy: src=nw_setup.sh dest=/usr/bin/nw_setup.sh mode=0755

- name: install ntp
  yum: name=ntp state=present
  when: ansible_os_family == "RedHat"

- name: start ntp
  shell: systemctl enable ntpd
  when: ansible_os_family == "RedHat"

- name: copy environment file for netmaster
  copy: src=netmaster.env dest=/etc/default/netmaster

- name: copy systemd units for netmaster
  copy: src=netmaster.service dest=/etc/systemd/system/netmaster.service

- name: setup netmaster host alias
  lineinfile: dest=/etc/hosts line="{{ contiv_service_vip }} netmaster"

- name: restart netmaster
  service: name=netmaster state=restarted

- name: configure network
  shell: nw_setup.sh
