
- name: copy netmaster exec file
  copy: src={{ contiv_bin_path }}/netmaster dest=/usr/bin/netmaster mode=0755

- name: copy netctl exec file
  copy: src={{ contiv_bin_path }}/netctl dest=/usr/bin/netctl mode=0755

- name: copy environment file for netmaster
  copy: src=netmaster.env dest=/etc/default/netmaster

- name: copy systemd units for netmaster
  copy: src=netmaster.service dest=/etc/systemd/system/netmaster.service

- name: setup netmaster host alias
  lineinfile: regexp=.*netmaster$ dest=/etc/hosts line="{{ contiv_service_vip }} netmaster"

- name: restart netmaster
  service: name=netmaster state=restarted

- include: aci.yml
  when: contiv_fabric_mode == "aci"

- include: default_network.yml
