
- name: copy netmaster exec file
  copy: src={{ contiv_bin_path }}/netmaster dest=/usr/bin/netmaster mode=0755

- name: copy netctl exec file
  copy: src={{ contiv_bin_path }}/netctl dest=/usr/bin/netctl mode=0755

- name: copy netmaster setup script
  copy: src=nw_setup.sh dest=/usr/bin/nw_setup.sh mode=0755

- name: copy environment file for netmaster
  copy: src=netmaster.env dest=/etc/default/netmaster

- name: copy systemd units for netmaster
  copy: src=netmaster.service dest=/etc/systemd/system/netmaster.service

- name: cleanup old netmaster host alias
  lineinfile: dest=/etc/hosts regexp=.*netmaster$ state=absent

- name: setup netmaster host alias
  lineinfile: regexp=.*netmaster$ dest=/etc/hosts line="{{ contiv_service_vip }} netmaster"

- name: restart netmaster
  shell: systemctl daemon-reload && systemctl start netmaster

- name: wait for netmaster
  action: shell netctl tenant ls
  register: netctl_res
  until: netctl_res.stdout.find("default") != -1
  retries: 7
  delay: 10

- include: aci.yml

- name: configure network
  shell: nw_setup.sh
